package com.onboarding.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "user_quizzes")
public class UserQuiz {
    @Id
    private String id;
    private String userId;
    private String quizId;
    private boolean completed;
    private int score; // Score out of 100
    private int maxScore = 100; // Maximum possible score
    private String completedAt; // Timestamp when the quiz was completed
    // TODO: Add fields for assessment results (e.g., score, submission date)

    // Constructors
    public UserQuiz() {
    }

    public UserQuiz(String userId, String quizId, boolean completed) {
        this.userId = userId;
        this.quizId = quizId;
        this.completed = completed;
    }

    public UserQuiz(String userId, String quizId, boolean completed, int score, String completedAt) {
        this.userId = userId;
        this.quizId = quizId;
        this.completed = completed;
        this.score = score;
        this.completedAt = completedAt;
    }

    // Getters and Setters are generated by @Data
}