package com.onboarding.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@Document(collection = "user_progress")
public class UserProgress {
    @Id
    private String id;
    private String userId;
    private String moduleId;
    private String status; // e.g., "NOT_STARTED", "IN_PROGRESS", "COMPLETED"
    private int completionPercentage;
    private LocalDateTime lastAccessedAt;
    private LocalDateTime completedAt;
    private List<String> completedSubModuleIds = new ArrayList<>(); // New field to store completed sub-module IDs
    private boolean quizCompleted = false; // New field to track quiz completion

    // Constructors
    public UserProgress() {
    }

    public UserProgress(String userId, String moduleId, String status, int completionPercentage) {
        this.userId = userId;
        this.moduleId = moduleId;
        this.status = status;
        this.completionPercentage = completionPercentage;
        this.lastAccessedAt = LocalDateTime.now();
    }

    // Getters and Setters are generated by @Data
}