package com.onboarding.dto;

import lombok.Data;

@Data
public class TraineeStatsDto {
    private String userName;
    private int overallProgress;
    private int badgesEarned;
    private int totalBadges;
    private int completedAssessments;
    private int completedModulesCount;
    private int inProgressModulesCount;
    private int notStartedModulesCount;

    // Constructors (Lombok's @Data will generate a no-arg constructor)
    // You can add specific constructors if needed, but @Data handles basic ones.

    public TraineeStatsDto(String userName, int overallProgress, int badgesEarned, int totalBadges,
            int completedAssessments, int completedModulesCount, int inProgressModulesCount,
            int notStartedModulesCount) {
        this.userName = userName;
        this.overallProgress = overallProgress;
        this.badgesEarned = badgesEarned;
        this.totalBadges = totalBadges;
        this.completedAssessments = completedAssessments;
        this.completedModulesCount = completedModulesCount;
        this.inProgressModulesCount = inProgressModulesCount;
        this.notStartedModulesCount = notStartedModulesCount;
    }

    public TraineeStatsDto(int overallProgress, int badgesEarned, int totalBadges, int completedAssessments) {
        this.overallProgress = overallProgress;
        this.badgesEarned = badgesEarned;
        this.totalBadges = totalBadges;
        this.completedAssessments = completedAssessments;
    }

    // Getters and Setters are now generated by @Data
}